(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  let history=[],pending=[],ready=false,sourceText='';
  const roleCanEdit=()=>['owner','editor'].includes(CultivoRepository.getCurrentWorkspace()?.role);
  function message(text,type='error'){const node=$('assistantMessage');node.textContent=text;node.className=`message show ${type}`}
  function clear(){const node=$('assistantMessage');node.textContent='';node.className='message'}
  function bubble(role,text){const article=document.createElement('article');article.className=`assistant-bubble ${role}`;article.innerHTML=`<strong>${role==='user'?'Vos':'Growmanager IA'}</strong><p>${esc(text)}</p>`;$('assistantConversation').append(article);article.scrollIntoView({block:'nearest'})}
  function proposalLabel(p){return({schedule_irrigation:'Programar un riego',record_irrigation:'Registrar riego realizado',create_event:'Crear evento',update_event:'Actualizar evento',record_activity:'Registrar actividad',record_incident:'Registrar incidente'}[p.type]||p.type)}
  function renderProposal(value){pending=Array.isArray(value)?value.filter(p=>p?.type&&p.type!=='none'):(value?.type&&value.type!=='none'?[value]:[]);const node=$('assistantProposal');if(!pending.length){node.hidden=true;node.innerHTML='';return}node.hidden=false;node.innerHTML=`<strong>${pending.length} ${pending.length===1?'acción propuesta':'acciones propuestas'}</strong><div class="ai-action-list">${pending.map((p,i)=>`<article class="ai-action-card"><strong>${i+1}. ${esc(proposalLabel(p))}</strong><span>${esc(p.summary||'Revisá los datos antes de confirmar.')}</span></article>`).join('')}</div><div class="assistant-proposal-actions"><button class="secondary-button compact" type="button" data-ai-cancel>Descartar</button>${roleCanEdit()?'<button class="primary-button compact" type="button" data-ai-confirm>Confirmar todo y guardar</button>':'<span class="field-help">Tu rol es de lectura.</span>'}</div>`}
  async function metadata(p){const[cs,lots,recipes]=await Promise.all(['cultivations','lots','recipes'].map(x=>CultivoRepository.getAll(x)));return{source:'ai_assistant',sourceText,cultivationId:p.cultivationId||null,cultivationName:cs.find(x=>x.id===p.cultivationId)?.name||null,lotId:p.lotId||null,lotName:lots.find(x=>x.id===p.lotId)?.name||null,recipeId:p.recipeId||null,recipeName:recipes.find(x=>x.id===p.recipeId)?.name||null}}
  async function applyOne(p){const x=p.payload||{};if(p.type==='schedule_irrigation'){if(!x.scheduledAt&&!x.startsAt)throw new Error('La propuesta no tiene fecha y hora.');return CultivoRepository.createIrrigation({cultivationId:x.cultivationId||null,lotId:x.lotId||null,scheduledAt:new Date(x.scheduledAt||x.startsAt).toISOString(),status:'planned',waterLiters:x.waterLiters??null,ph:x.ph??null,ec:x.ec??null,notes:x.notes||x.description||'',supplies:x.supplies||[]})}if(p.type==='record_irrigation')return CultivoRepository.createIrrigation({cultivationId:x.cultivationId||null,lotId:x.lotId||null,scheduledAt:new Date(x.occurredAt||Date.now()).toISOString(),completedAt:new Date(x.occurredAt||Date.now()).toISOString(),status:'completed',waterLiters:x.waterLiters??null,ph:x.ph??null,ec:x.ec??null,notes:x.details||x.notes||'',supplies:x.supplies||[]});if(p.type==='record_activity'||p.type==='record_incident')return CultivoRepository.createOperationLog({kind:p.type==='record_incident'?'incident':'activity',category:x.category||x.type||'general',title:x.title||p.summary||'Registro del asistente',description:x.description||x.details||x.observations||'',severity:x.severity||'info',occurredAt:new Date(x.occurredAt||Date.now()).toISOString(),metadata:await metadata(x)});if(p.type==='create_event'){const start=new Date(x.startsAt||Date.now());return CultivoRepository.saveAgendaEvent({title:x.title||'Actividad',eventType:x.eventType||'other',startsAt:start.toISOString(),endsAt:new Date(x.endsAt||start.getTime()+3600000).toISOString(),cultivationId:x.cultivationId||null,lotId:x.lotId||null,description:x.description||'',priority:x.priority||'normal',status:x.status||'pending',recurrence:'none',assignees:[],participants:[]})}throw new Error(`La acción ${proposalLabel(p)} todavía no está soportada en esta pantalla.`)}
  async function applyProposal(){if(!pending.length||!roleCanEdit())return;for(const p of pending)await applyOne(p);renderProposal(null);await Agenda.load();await Operations.load();message('Acciones guardadas en Supabase y visibles en la Bitácora.','success');bubble('assistant','Listo. Quedaron registradas en la bitácora compartida del proyecto.')}
  async function ask(text,button){clear();sourceText=text;bubble('user',text);history.push({role:'user',text});button.disabled=true;button.textContent='Consultando…';try{const workspace=CultivoRepository.getCurrentWorkspace();if(!workspace)throw new Error('Seleccioná un proyecto.');const deviceContext=await globalThis.GrowDevice?.getAssistantContext?.();const{data,error}=await GrowSupabase.client.functions.invoke('grow-assistant',{body:{message:text,history:history.slice(-9,-1),workspaceId:workspace.id,deviceContext}});if(error)throw error;if(!data?.reply)throw new Error(data?.message||'Gemini no devolvió una respuesta válida.');bubble('assistant',data.reply);history.push({role:'assistant',text:data.reply});renderProposal(data.proposals||data.proposal)}catch(error){console.error(error);message(error.message||'No se pudo consultar el asistente.')}finally{button.disabled=false;button.textContent='Enviar'}}
  function init(){if(ready)return;ready=true;$('assistantForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,text=form.elements.message.value.trim();if(!text)return;form.elements.message.value='';ask(text,event.submitter)});$('assistantProposal').addEventListener('click',async event=>{if(event.target.closest('[data-ai-cancel]')){renderProposal(null);message('Propuesta descartada.','info')}if(event.target.closest('[data-ai-confirm]')){const button=event.target.closest('[data-ai-confirm]');button.disabled=true;try{await applyProposal()}catch(error){message(error.message,'error');button.disabled=false}}});addEventListener('grow-workspace-changed',()=>{history=[];renderProposal(null);bubble('assistant','Cambiaste de proyecto. El contexto del asistente fue reiniciado.')})}
  async function refresh(){if(!CultivoRepository.getCurrentWorkspace())return;clear()}
  globalThis.GrowAssistant=Object.freeze({init,refresh});
})();
