(() => {
  'use strict';
  let gate,app,onSession,currentUser=null;
  const client=()=>GrowSupabase.client;
  function message(text,type='error'){const node=document.getElementById('authMessage');node.textContent=text;node.className=`message show ${type}`}
  function friendly(error){console.error('Supabase Auth:',error);const text=(error?.message||'').toLowerCase();if(text.includes('invalid login'))return'Email o contraseña incorrectos.';if(text.includes('email not confirmed'))return'Confirmá tu email antes de iniciar sesión.';if(text.includes('already registered'))return'Ya existe una cuenta con ese email.';if(text.includes('password'))return'La contraseña debe tener al menos 6 caracteres.';if(text.includes('fetch')||text.includes('network'))return'No se pudo conectar con Supabase.';return'No se pudo completar la autenticación.'}
  function callbackUrl(){const url=new URL('.',location.href);url.search='';url.hash='';return url.href}
  async function applySession(session){currentUser=session?.user||null;gate.hidden=Boolean(currentUser);app.hidden=!currentUser;document.getElementById('cloudAccount').hidden=!currentUser;document.getElementById('cloudEmail').textContent=currentUser?.email||'';document.getElementById('mobileCloudStatus').textContent=currentUser?'Nube conectada':'Sin sesión';CultivoRepository.resetSession();if(currentUser)await onSession(currentUser)}
  async function submit(event){event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));const action=event.submitter?.dataset.authAction||'login';const button=event.submitter;button.disabled=true;message(action==='register'?'Creando cuenta…':'Iniciando sesión…','info');try{if(action==='register'){const{data:result,error}=await client().auth.signUp({email:data.email,password:data.password,options:{emailRedirectTo:callbackUrl()}});if(error)throw error;if(!result.session){message('Cuenta creada. Revisá tu email para confirmarla y luego iniciá sesión.','success');return}}else{const{error}=await client().auth.signInWithPassword({email:data.email,password:data.password});if(error)throw error}}catch(error){message(friendly(error))}finally{button.disabled=false}}
  async function signOut(){const{error}=await client().auth.signOut();if(error)message(friendly(error));else location.reload()}
  async function init(callback){gate=document.getElementById('authGate');app=document.getElementById('appLayout');onSession=callback;if(!GrowSupabase.configured){message('Falta configurar la conexión pública con Supabase.');return}document.getElementById('authForm').addEventListener('submit',submit);document.getElementById('signOutButton').addEventListener('click',signOut);client().auth.onAuthStateChange((_event,session)=>setTimeout(()=>applySession(session),0));const{data,error}=await client().auth.getSession();if(error)message(friendly(error));else await applySession(data.session)}
  function getUser(){return currentUser}
  globalThis.GrowAuth=Object.freeze({init,getUser,signOut});
})();
