(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),$=id=>document.getElementById(id),M=()=>CultivoModels;
let root,rooms=[],crops=[],records=[],plants=[],busy=false;
const editable=()=>['owner','editor'].includes(CultivoRepository.getCurrentWorkspace()?.role),stage=v=>M().LOT_STAGE_LABELS[v]||v;
function message(text,error=false){const n=$('cultivationMessage');n.textContent=text;n.className=`message show ${error?'error':'success'}`}
const tone=c=>c.currentStage==='flowering'?'flowering':['mother','clone','rooting','vegetative'].includes(c.currentStage)?'vegetative':'neutral';
const menu=(label,actions)=>`<details class="action-menu"><summary aria-label="${esc(label)}">⋯</summary><div class="action-menu-items">${actions}</div></details>`;
const cropDate=value=>value?new Intl.DateTimeFormat('es-AR',{dateStyle:'short'}).format(new Date(value+'T12:00:00')):'—';
const originName=v=>({clone:'Esquejes',seed:'Semillas',seedling:'Plantines',unknown:'Origen sin definir'})[v]||v;
function groupRow(){return `<div class="plant-batch-row"><label>Cepa<input data-batch="variety" list="knownStrains" required maxlength="100" placeholder="Ej. Orange Blossom"></label><label>Origen<select data-batch="origin">${options([['clone','Esqueje'],['seed','Semilla'],['seedling','Plantín'],['unknown','Sin definir']],'clone')}</select></label><label>Cantidad<input data-batch="count" type="number" min="1" max="500" step="1" required value="1"></label><label>Semanas de flora<input data-batch="floweringWeeks" type="number" min="1" max="52" step="1" placeholder="Sin definir"></label><button type="button" class="text-button" data-remove-batch>Quitar</button></div>`}
function batchFields(optional=false){return `<fieldset><legend>Plantas por grupo${optional?' · opcional':''}</legend><datalist id="knownStrains">${[...new Set(plants.map(p=>p.variety).filter(Boolean))].map(v=>`<option value="${esc(v)}"></option>`).join('')}</datalist><div id="plantBatchRows">${optional?'':groupRow()}</div><button type="button" class="secondary-button" data-add-batch>+ Agregar otra cepa</button><p id="plantBatchTotal" class="field-help"></p></fieldset>`}
function selectionFields(list){return `<fieldset><legend>Seleccioná grupos, cantidades o plantas</legend>${M().plantGroups(list).map(g=>`<section class="plant-selection-group"><label class="check-field"><input type="checkbox" data-select-group>${esc(g.variety)} · ${originName(g.origin)} · ${g.plants.length} plantas</label><label>Cantidad a seleccionar<input type="number" data-select-count min="0" max="${g.plants.length}" value="0" step="1"></label><details><summary>Elegir plantas individuales</summary>${g.plants.map(p=>`<label class="check-field"><input type="checkbox" name="plantIds" value="${p.id}">${esc(p.code)} · ${esc(p.status)}</label>`).join('')}</details></section>`).join('')||'<p>Sin plantas registradas.</p>'}<p id="plantSelectionTotal" class="field-help">0 plantas seleccionadas</p></fieldset>`}
function cropGroupCards(c,record){const list=plants.filter(p=>p.lotId===record?.id);return list.length?`<details class="crop-plant-groups"><summary>Plantas por grupo · ${list.length}</summary>${M().plantGroups(list).map(g=>{const date=M().floweringDates(c.stageStartedOn,[g]).end;return `<div><strong>${esc(g.variety)} · ${g.plants.length} ${esc(originName(g.origin).toLowerCase())}</strong><small>${g.floweringWeeks?`${g.floweringWeeks} semanas de flora`:'Semanas de flora pendientes'}${c.currentStage==='flowering'&&date?' · Fin estimado '+cropDate(date):''}</small></div>`}).join('')}${editable()?`<button class="text-button" data-manage-plants="${record.id}">Gestionar selección</button>`:''}</details>`:''}
function cropCard(c){const record=records.find(l=>l.cultivationId===c.id),count=plants.filter(p=>p.lotId===record?.id&&p.status==='active').length,start=new Date((c.startDate||'')+'T12:00:00'),week=Number.isNaN(start.getTime())?'—':Math.max(1,Math.floor((new Date()-start)/604800000)+1);return `<article class="lot-card crop-summary" data-crop-tone="${tone(c)}"><div class="crop-summary-main"><button class="text-button lot-title" ${record?`data-open-lot="${record.id}"`:'disabled'}>${esc(c.name)} →</button><div class="crop-facts"><span class="crop-stage" data-crop-tone="${c.currentStage==='flowering'?'flowering':['mother','clone','rooting','vegetative'].includes(c.currentStage)?'vegetative':'neutral'}">${esc(stage(c.currentStage))}</span>${c.status==='planned'?'<span>Inicio previsto</span>':`<span>Semana ${week}</span>`}<span>${count} plantas</span>${c.status!=='active'?`<span>${M().CULTIVATION_STATUS_LABELS[c.status]||c.status}</span>`:''}</div><p class="field-help">Inicio ${cropDate(c.startDate)} · ${c.cultivationMode==='continuous'?'Continuo / madres':`Fin estimado ${cropDate(c.plannedEndDate)}`}</p>${c.notes?`<details class="crop-notes"><summary>Notas</summary><p>${esc(c.notes)}</p></details>`:''}${cropGroupCards(c,record)}${editable()&&record&&['active','planned'].includes(c.status)?`<button class="text-button compact" data-add-plants="${record.id}">Agregar plantas</button>`:''}</div>${editable()?menu('Acciones de '+c.name,`<button class="text-button" data-crop-edit="${c.id}">Editar cultivo</button>${c.status==='planned'?`<button class="text-button" data-crop-start="${c.id}">Iniciar cultivo</button>`:''}${['active','planned'].includes(c.status)?`<button class="text-button" data-crop-move="${c.id}">Trasladar</button><button class="text-button" data-crop-finish="${c.id}">Finalizar</button>`:''}<button class="text-button" data-crop-delete="${c.id}">Eliminar</button>`):''}</article>`}
function render(){root.innerHTML=`<div id="cultivationMessage" class="message" role="status"></div><div class="section-heading"><div><h3>Tus salas</h3><p class="subtle">Cada sala reúne sus cultivos y plantas.</p></div>${editable()?'<button class="primary-button" data-room-new>+ Nueva sala</button>':''}</div>${rooms.map(r=>{const current=crops.filter(c=>c.roomId===r.id&&['active','planned'].includes(c.status)),history=crops.filter(c=>c.roomId===r.id&&!['active','planned'].includes(c.status));return `<section class="panel space-card room-container" data-crop-tone="${r.role==='outdoor'?'outdoor':'neutral'}"><header class="room-heading"><div><p class="eyebrow">${r.role==='outdoor'?'Exterior':'Interior'}${r.active?'':' · Inactiva'}</p><h3>${esc(r.name)}</h3><small>${r.lengthM&&r.widthM&&r.heightM?`${Number(r.lengthM)} × ${Number(r.widthM)} × ${Number(r.heightM)} m · ${(r.lengthM*r.widthM*r.heightM).toLocaleString('es-AR',{maximumFractionDigits:2})} m³ · `:'Dimensiones pendientes · '}${current.filter(c=>c.status==='active').length} activos · ${current.filter(c=>c.status==='planned').length} planificados</small>${r.description?`<p class="subtle">${esc(r.description)}</p>`:''}</div>${editable()?menu('Acciones de '+r.name,`<button class="text-button" data-room-edit="${r.id}">Editar sala</button><button class="text-button" data-room-delete="${r.id}">Eliminar sala</button>`):''}</header><div class="environment-room-summary" data-room-environment="${r.id}"></div><button class="text-button" type="button" data-open-room-environment="${r.id}">Ver ambiente →</button><div class="room-crops">${current.map(cropCard).join('')||'<p class="field-help">Sin cultivos activos.</p>'}${r.active&&editable()?`<button class="secondary-button" data-crop-new="${r.id}">+ Crear cultivo</button>`:''}${history.length?`<details class="history-panel"><summary>Cultivos anteriores · ${history.length}</summary>${history.map(cropCard).join('')}</details>`:''}</div></section>`}).join('')||'<section class="empty-state"><h3>Creá tu primera sala</h3><p>Definí su nombre; después agregá el cultivo y sus plantas.</p></section>'}<dialog id="cultivationDialog" class="app-dialog"></dialog>`;dispatchEvent(new CustomEvent("grow-rooms-rendered"))}

const options=(list,value)=>list.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
function open(kind,id,roomId){if(!editable())return;const dialog=$('cultivationDialog'),x=(kind==='room'?rooms:kind==='plant'?plants:crops).find(c=>c.id===id)||{};let fields='';
if(kind==='room')fields=`<label>Nombre de la sala<input name="name" value="${esc(x.name||'')}" required maxlength="100"></label><label>Ubicación<select name="role">${options([['vegetative','Interior'],['outdoor','Exterior']],x.role==='outdoor'?'outdoor':'vegetative')}</select></label><fieldset class="room-dimensions"><legend>Tamaño de la sala</legend><div class="dimension-grid">${[["lengthM","Largo"],["widthM","Ancho"],["heightM","Alto"]].map(([key,label])=>`<label>${label} (m)<input name="${key}" type="number" min="0.01" max="1000" step="0.01" value="${esc(x[key]??'')}" required></label>`).join('')}</div><p id="roomVolume" class="field-help"></p></fieldset><label>Descripción<textarea name="description">${esc(x.description||'')}</textarea></label><label class="check-field"><input type="checkbox" name="active" ${x.active!==false?'checked':''}> Sala activa</label>`;
if(kind==='crop')fields=`<p class="field-help">Sala: ${esc(rooms.find(r=>r.id===(x.roomId||roomId))?.name)}</p><label>Nombre del cultivo<input name="name" required maxlength="120" value="${esc(x.name||'')}"></label><div class="form-grid two"><label>Seguimiento<select name="cultivationMode">${options([['cycle','Por ciclo'],['continuous','Continuo / madres']],x.cultivationMode||'cycle')}</select></label><label>Etapa<select name="currentStage">${options(M().LOT_STAGES.map(s=>[s,stage(s)]),x.currentStage||'vegetative')}</select></label><label>Inicio<input type="date" name="startDate" required value="${x.startDate||new Date().toISOString().slice(0,10)}"></label><label>Inicio de etapa<input type="date" name="stageStartedOn" required value="${x.stageStartedOn||new Date().toISOString().slice(0,10)}"></label><label>Fin estimado<input type="date" name="plannedEndDate" value="${x.plannedEndDate||''}"></label><label>Estado<select name="status">${options([['planned','Planificado'],['active','Activo'],['finished','Finalizado'],['archived','Archivado']],x.status||'planned')}</select></label><label>Fin real<input type="date" name="endDate" value="${x.endDate||''}"></label></div><label>Notas<textarea name="notes">${esc(x.notes||'')}</textarea></label>`;
if(kind==='crop')fields+=`<p id="floweringDateHint" class="field-help"></p>${id?'':batchFields(true)}`;
if(kind==='move')fields=`<label>Destino<select name="destinationRoom" required>${options(rooms.filter(r=>r.active).map(r=>[r.id,r.name]),'')}</select></label><label>Qué trasladar<select name="moveMode"><option value="crop">Cultivo completo a otra sala</option><option value="all">Todas las plantas a otro cultivo</option><option value="selected">Plantas seleccionadas</option></select></label><label>Cultivo de destino<select name="destinationCrop"><option value="">Seleccionar cultivo</option>${options(crops.filter(c=>['active','planned'].includes(c.status)&&c.id!==id).map(c=>[c.id,c.name+' · '+rooms.find(r=>r.id===c.roomId)?.name]),'')}</select></label>${selectionFields(plants.filter(p=>p.lotId===records.find(l=>l.cultivationId===id)?.id&&p.status==='active'))}`;
if(kind==='plants')fields=batchFields();
if(kind==='manage')fields=`${selectionFields(plants.filter(p=>p.lotId===id))}<label>Estado para la selección<select name="batchStatus"><option value="">Mantener actual</option><option value="active">Activa</option><option value="harvested">Cosechada</option><option value="inactive">Inactiva</option></select></label><label>Semanas de flora para la selección<input name="batchWeeks" type="number" min="1" max="52" placeholder="Mantener actuales"></label><label class="check-field"><input type="checkbox" name="replaceNotes"> Aplicar la misma nota a la selección</label><label>Nota<textarea name="batchNotes"></textarea></label><button type="button" class="secondary-button" data-transfer-selection="${id}">Trasladar selección</button>`;
if(kind==='plant')fields=`<div class="form-grid two"><label>Origen<select name="origin">${options([['unknown','Sin definir'],['clone','Esqueje'],['seed','Semilla'],['seedling','Plantín']],x.origin||'unknown')}</select></label><label>Semanas de flora<input type="number" name="floweringWeeks" min="1" max="52" value="${x.floweringWeeks||''}"></label></div><label>Identificación<input name="code" required value="${esc(x.code)}"></label><label>Variedad<input name="variety" value="${esc(x.variety)}"></label><label>Estado<select name="status">${options([['active','Activa'],['harvested','Cosechada'],['inactive','Inactiva']],x.status)}</select></label><label>Notas<textarea name="notes">${esc(x.notes)}</textarea></label>`;
dialog.classList.toggle('plant-management-dialog',['crop','plants','manage','move'].includes(kind));dialog.innerHTML=`<form class="dialog-form" data-kind="${kind}" data-id="${id||''}" data-room="${x.roomId||roomId||''}" data-workspace="${CultivoRepository.getCurrentWorkspace()?.id||''}"><div class="dialog-heading"><h3>${kind==='move'?'Trasladar cultivo o plantas':kind==='plants'?'Agregar plantas':kind==='manage'?'Gestionar plantas':`${id?'Editar':'Crear'} ${kind==='room'?'sala':kind==='plant'?'planta':'cultivo'}`}</h3><button type="button" class="icon-button" value="cancel" aria-label="Cerrar">×</button></div>${fields}<p class="message" role="status" id="cropFormMessage"></p><div class="form-actions"><button type="button" class="secondary-button" value="cancel">Cancelar</button><button type="submit" class="primary-button">Guardar</button></div></form>`;dialog.showModal();wireForm(dialog,kind,id);if(kind==='room'){const volume=()=>{const n=['lengthM','widthM','heightM'].map(k=>Number(dialog.querySelector(`[name=${k}]`).value));$('roomVolume').textContent=n.every(v=>v>0)?`Volumen: ${n.reduce((a,b)=>a*b,1).toLocaleString('es-AR',{maximumFractionDigits:2})} m³`:'Ingresá las tres medidas para calcular el volumen.'};dialog.querySelectorAll('input[type=number]').forEach(n=>n.addEventListener('input',volume));volume()}}
function batches(dialog){return [...dialog.querySelectorAll('.plant-batch-row')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-batch]')].map(n=>[n.dataset.batch,n.dataset.batch==='count'?Number(n.value):n.dataset.batch==='floweringWeeks'?(n.value?Number(n.value):null):n.value.trim()])))}
function wireForm(dialog,kind,id){const form=dialog.querySelector('form');const update=()=>{if(kind==='move'){const mode=form.elements.moveMode.value;form.elements.destinationCrop.closest('label').hidden=mode==='crop';form.querySelector('fieldset').hidden=mode!=='selected';}const groups=batches(dialog),total=groups.reduce((n,g)=>n+g.count,0);if($('plantBatchTotal'))$('plantBatchTotal').textContent=`Se crearán ${total} plantas en ${groups.length} grupos.`;if(kind==='crop'){form.elements.endDate.closest('label').hidden=!['finished','archived'].includes(form.elements.status.value);const crop=crops.find(c=>c.id===id),lot=records.find(l=>l.cultivationId===id),existing=M().plantGroups(plants.filter(p=>p.lotId===lot?.id&&p.status!=='inactive')),flower=form.elements.currentStage.value==='flowering'&&form.elements.cultivationMode.value==='cycle',result=M().floweringDates(form.elements.stageStartedOn.value,[...existing,...groups]);form.elements.plannedEndDate.readOnly=flower;if(flower)form.elements.plannedEndDate.value=result.end||'';$('floweringDateHint').textContent=flower?(result.missing?'Definí las semanas de flora de cada cepa para calcular el fin.':result.dates.map(g=>`${g.variety}: ${cropDate(g.end)}`).join(' · ')):'';}};
 const selection=()=>{if($('plantSelectionTotal'))$('plantSelectionTotal').textContent=`${dialog.querySelectorAll('[name=plantIds]:checked').length} plantas seleccionadas`;};
 dialog.oninput=e=>{if(e.target.matches('[data-select-count]')){const section=e.target.closest('section'),count=Math.max(0,Math.min(Number(e.target.value)||0,Number(e.target.max)));section.querySelectorAll('[name=plantIds]').forEach((n,i)=>n.checked=i<count);section.querySelector('[data-select-group]').checked=count===Number(e.target.max);selection();}update()};
 dialog.onchange=e=>{if(e.target.name==='destinationRoom'){form.elements.destinationCrop.innerHTML='<option value="">Seleccionar cultivo</option>'+options(crops.filter(c=>['active','planned'].includes(c.status)&&c.id!==id&&c.roomId===e.target.value).map(c=>[c.id,c.name]),'');}if(e.target.matches('[data-batch=variety]')){const p=plants.find(p=>p.variety.toLowerCase()===e.target.value.trim().toLowerCase()&&p.floweringWeeks);if(p)e.target.closest('.plant-batch-row').querySelector('[data-batch=floweringWeeks]').value=p.floweringWeeks;}if(e.target.matches('[data-select-group]')){const section=e.target.closest('section');section.querySelectorAll('[name=plantIds]').forEach(n=>n.checked=e.target.checked);section.querySelector('[data-select-count]').value=e.target.checked?section.querySelectorAll('[name=plantIds]').length:0;}if(e.target.name==='plantIds'){const section=e.target.closest('section'),count=section.querySelectorAll('[name=plantIds]:checked').length;section.querySelector('[data-select-count]').value=count;section.querySelector('[data-select-group]').checked=count===section.querySelectorAll('[name=plantIds]').length;}selection();update();};
 dialog.onclick=e=>{if(e.target.closest('[data-add-batch]')){$('plantBatchRows').insertAdjacentHTML('beforeend',groupRow());update()}if(e.target.closest('[data-remove-batch]')){e.target.closest('.plant-batch-row').remove();update()}const transfer=e.target.closest('[data-transfer-selection]');if(transfer){const ids=[...dialog.querySelectorAll('[name=plantIds]:checked')].map(n=>n.value);if(!ids.length){$('cropFormMessage').textContent='Seleccioná plantas para trasladar.';return}if(ids.some(id=>plants.find(p=>p.id===id)?.status!=='active')){$('cropFormMessage').textContent='Para trasladar, seleccioná únicamente plantas activas.';return}const record=records.find(l=>l.id===transfer.dataset.transferSelection);open('move',record.cultivationId);const newForm=dialog.querySelector('form');newForm.elements.moveMode.value='selected';newForm.elements.moveMode.dispatchEvent(new Event('change',{bubbles:true}));dialog.querySelectorAll('[name=plantIds]').forEach(n=>n.checked=ids.includes(n.value));dialog.querySelectorAll('.plant-selection-group').forEach(section=>{const count=section.querySelectorAll('[name=plantIds]:checked').length;section.querySelector('[data-select-count]').value=count;section.querySelector('[data-select-group]').checked=count===section.querySelectorAll('[name=plantIds]').length;});$('plantSelectionTotal').textContent=`${ids.length} plantas seleccionadas`;}};if(kind==='move')dialog.onchange({target:form.elements.destinationRoom});update();}
async function load(){if($('cultivationDialog')?.open)return;const workspace=CultivoRepository.getCurrentWorkspace()?.id;const data=await Promise.all(['rooms','cultivations','lots','plants'].map(s=>CultivoRepository.getAll(s)));if(workspace!==CultivoRepository.getCurrentWorkspace()?.id||$('cultivationDialog')?.open)return;[rooms,crops,records,plants]=data;render()}
async function submit(e){const f=e.target.closest('[data-kind]');if(!f)return;e.preventDefault();if(busy)return;busy=true;const button=f.querySelector('[type=submit]');button.disabled=true;const d=Object.fromEntries(new FormData(f)),id=f.dataset.id,kind=f.dataset.kind;try{
 if(f.dataset.workspace!==CultivoRepository.getCurrentWorkspace()?.id||!editable())throw new Error('El proyecto o tus permisos cambiaron. Volvé a abrir el formulario.');
 if(kind==='room'){const value={name:d.name.trim(),role:d.role,description:d.description,active:d.active==='on',lengthM:Number(d.lengthM),widthM:Number(d.widthM),heightM:Number(d.heightM)};if(![value.lengthM,value.widthM,value.heightM].every(n=>Number.isFinite(n)&&n>0&&n<=1000))throw new Error('Ingresá largo, ancho y alto mayores que cero.');if(id)await CultivoRepository.update('rooms',id,value);else await CultivoRepository.create('rooms',value)}
 if(kind==='crop'){const value=M().assertValid(M().validateCultivation({...d,roomId:f.dataset.room,plannedEndDate:d.cultivationMode==='continuous'?null:d.plannedEndDate||null,endDate:d.endDate||null}));value.roomId=f.dataset.room;if(id)await CultivoRepository.update('cultivations',id,value);else await CultivoRepository.cropAction('create_crop_with_groups',{p_workspace_id:f.dataset.workspace,p_crop:value,p_groups:batches(f)})}
 if(kind==='move'){const target=d.moveMode==='crop'?null:d.destinationCrop;if(d.moveMode!=='crop'&&!target)throw new Error('Elegí un cultivo de destino.');if(target&&crops.find(c=>c.id===target)?.roomId!==d.destinationRoom)throw new Error('El cultivo de destino debe pertenecer a la sala seleccionada.');await CultivoRepository.cropAction('move_crop',{p_crop:id,p_room:d.destinationRoom,p_target_crop:target,p_plants:d.moveMode==='selected'?new FormData(f).getAll('plantIds'):null})}
 if(kind==='plants')await CultivoRepository.cropAction('add_crop_plant_groups',{p_lot_id:id,p_groups:batches(f)});
 if(kind==='manage'){const ids=new FormData(f).getAll('plantIds');if(!ids.length)throw new Error('Seleccioná al menos una planta.');if(!d.batchStatus&&!d.batchWeeks&&!d.replaceNotes)throw new Error('Elegí un cambio para aplicar.');await CultivoRepository.cropAction('manage_crop_plants',{p_lot_id:id,p_ids:ids,p_status:d.batchStatus||null,p_notes:d.replaceNotes?d.batchNotes:null,p_weeks:d.batchWeeks?Number(d.batchWeeks):null})}
 if(kind==='plant')await CultivoRepository.update('plants',id,{...d,floweringWeeks:d.floweringWeeks?Number(d.floweringWeeks):null});
 $('cultivationDialog').close();await load();message('Cambios guardados.');await GrowToday.refreshCrop();
}catch(error){const n=$('cropFormMessage');if(n){n.textContent=error.message;n.className='message show error'}else message('Cambios guardados; actualizá la vista para recargar.',true)}finally{busy=false;button.disabled=false}}
function init(){root=$('cultivationRoot');root.addEventListener('submit',submit);root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;b.closest('details.action-menu')?.removeAttribute('open');if(b.value==='cancel'){b.closest('dialog')?.close();return}if(b.hasAttribute('data-room-new'))open('room');if(b.dataset.roomEdit)open('room',b.dataset.roomEdit);if(b.dataset.cropNew)open('crop',null,b.dataset.cropNew);if(b.dataset.cropEdit)open('crop',b.dataset.cropEdit);if(b.dataset.cropMove)open('move',b.dataset.cropMove);try{if(b.dataset.cropFinish&&confirm('¿Finalizar este cultivo? Se conserva su historial.')){await CultivoRepository.update('cultivations',b.dataset.cropFinish,{status:'finished',endDate:new Date().toISOString().slice(0,10)});await load()}if(b.dataset.cropDelete&&confirm('¿Eliminar el cultivo? Solo se eliminan cultivos sin plantas ni historial.')){await CultivoRepository.cropAction('delete_empty_crop',{p_crop:b.dataset.cropDelete});await load()}if(b.dataset.roomDelete){if(crops.some(c=>c.roomId===b.dataset.roomDelete))throw new Error('La sala tiene cultivos. Trasladalos o conservá la sala inactiva para su historial.');if(confirm('¿Eliminar esta sala vacía?')){await CultivoRepository.remove('rooms',b.dataset.roomDelete);await load()}}}catch(error){message(error.message,true)}});document.addEventListener('click',async e=>{const b=e.target.closest('[data-add-plants],[data-edit-plant],[data-manage-plants]');if(!b)return;try{await GrowNavigation.showView('cultivation');await load();if(b.dataset.addPlants)open('plants',b.dataset.addPlants);else if(b.dataset.managePlants)open('manage',b.dataset.managePlants);else open('plant',b.dataset.editPlant)}catch(error){message(error.message,true)}})}
async function startCrop(id){if(!editable())return;if(!confirm('¿Iniciar este cultivo hoy? Pasará de Planificado a Activo.'))return;await CultivoRepository.cropAction('start_planned_crop',{p_crop:id});await load();await GrowToday.refreshCrop();await Agenda.load()}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-crop-start]');if(b){b.disabled=true;try{await startCrop(b.dataset.cropStart)}catch(error){message(error.message,true)}finally{b.disabled=false}}});
 globalThis.Cultivation=Object.freeze({init,load,startCrop,async editLot(id){await load();const record=records.find(l=>l.id===id);if(record)open('crop',record.cultivationId)}});
})();
