(()=>{'use strict';
const KEY='growmanager.environment.v1',WINDOW=48*3600000,SAMPLE=300000,MAX=1200,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let lastCloudSync=0,request=0;
const valid=(t,h)=>EnvironmentModels.valid(t,h),deviceKey=a=>String(a||'primary-wemos').trim().toLowerCase().replace(/[^a-z0-9.:-]/g,'-').slice(0,80);
function load(){try{const r=JSON.parse(localStorage.getItem(KEY));return Array.isArray(r)?r:[]}catch{return[]}}
function localRows(device){return load().filter(r=>r.device===device&&Date.now()-r.at<=WINDOW&&valid(r.temperature,r.humidity)).sort((a,b)=>a.at-b.at)}
function track(s,address){if(s?.dht?.fresh===false||!valid(s?.temperature,s?.humidity))return false;const now=Date.now(),device=deviceKey(address),rows=load().filter(r=>now-r.at<=WINDOW),last=rows.filter(r=>r.device===device).at(-1);if(last&&now-last.at<SAMPLE)return false;const sample={at:now,temperature:s.temperature,humidity:s.humidity,device,payload:{environment:s.environment,relays:s.relays,dht:s.dht}};rows.push(sample);localStorage.setItem(KEY,JSON.stringify(rows.slice(-MAX)));if(now-lastCloudSync>SAMPLE&&globalThis.CultivoRepository?.getCurrentWorkspace?.()){lastCloudSync=now;CultivoRepository.saveEnvironmentReading({deviceKey:device,sampledAt:now,temperature:s.temperature,humidity:s.humidity}).catch(()=>{lastCloudSync=0})}return true}
function render(rows,metric,source){const start=Date.now()-WINDOW,key=metric==='vpd'?'vpd':metric,unit=key==='temperature'?'°C':key==='humidity'?'%':'kPa';rows=rows.filter(r=>valid(r.temperature,r.humidity)&&r.payload?.dht?.fresh!==false&&r.at>=start).map(r=>({...r,vpd:EnvironmentModels.vpd(r.temperature,r.humidity)}));const values=rows.map(r=>r[key]);const targets=key==='vpd'?rows.flatMap(r=>{const e=r.payload?.environment;return e?[e.vpdMin,e.vpdMax].filter(Number.isFinite):[]}):[],all=[...values,...targets],lo=all.length?Math.max(key==='vpd'?0:-20,Math.min(...all)-(key==='vpd'?.15:1)):0,hi=all.length?Math.max(...all)+(key==='vpd'?.15:1):key==='vpd'?2:100;
 $('environmentHistoryStats').innerHTML=values.length?['Mínimo','Promedio','Máximo'].map((name,i)=>`<div><span>${name}</span><strong>${[Math.min(...values),values.reduce((a,b)=>a+b,0)/values.length,Math.max(...values)][i].toFixed(key==='vpd'?2:1)} ${unit}</strong></div>`).join(''):'<p>Sin muestras válidas.</p>';
 const x=t=>42+(t-start)/WINDOW*734,y=v=>220-(v-lo)/(hi-lo)*202,grid=[0,1,2,3,4].map(i=>`<line class="environment-grid" x1="42" y1="${18+i*50.5}" x2="776" y2="${18+i*50.5}"/><text class="environment-axis" x="2" y="${22+i*50.5}">${(hi-(hi-lo)*i/4).toFixed(key==='vpd'?2:0)}</text>`).join(''),labels=[48,36,24,12,0].map((h,i)=>`<text class="environment-axis" x="${42+i*183.5}" y="245" text-anchor="middle">${h?'-'+h+' h':'Ahora'}</text>`).join('');
 const bands=key==='vpd'?rows.map(r=>{const e=r.payload?.environment;if(!Number.isFinite(e?.vpdMin)||!Number.isFinite(e?.vpdMax))return'';return`<rect class="environment-target-band" x="${x(r.at)}" y="${y(e.vpdMax)}" width="${Math.max(0,Math.min(x(r.at+SAMPLE),776)-x(r.at))}" height="${y(e.vpdMin)-y(e.vpdMax)}"><title>Objetivo registrado ${e.vpdMin}–${e.vpdMax} kPa</title></rect>`}).join(''):'';
 let segments=[],segment=[];for(const row of rows){if(segment.length&&row.at-segment.at(-1).at>2*SAMPLE){segments.push(segment);segment=[]}segment.push(row)}if(segment.length)segments.push(segment);
 $('environmentHistoryChart').innerHTML=`<svg viewBox="0 0 800 255" role="img" aria-label="${esc(metric)} de las últimas 48 horas">${bands}${grid}${labels}${segments.map(a=>a.length>1?`<polyline class="environment-${key==='humidity'?'humidity':'temp'}-path" points="${a.map(r=>`${x(r.at)},${y(r[key])}`).join(' ')}"/>`:`<circle cx="${x(a[0].at)}" cy="${y(a[0][key])}" r="3" fill="currentColor"/>`).join('')}</svg>`;
 $('environmentHistoryLegend').textContent=`${key==='vpd'?'VPD del aire · Banda verde: objetivo registrado':key==='humidity'?'Humedad':'Temperatura'} · ${unit}`;
 $('environmentHistoryNote').textContent=`${rows.length} muestras ${source==='cloud'?'del proyecto':'del respaldo local'}. Intervalo aproximado: 5 minutos. Los huecos corresponden a períodos sin datos.${key==='vpd'?' Los objetivos sólo aparecen cuando fueron registrados; no se aplica el objetivo actual al pasado.':''}`;
}
function renderActions(events){let shown=60;const ascending=[...events].sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt)),items=ascending.map((e,i)=>({e,d:EnvironmentTimelineModels.eventDetails(e,ascending[i-1])})).reverse();
 const draw=()=>{$('environmentHistoryActions').innerHTML=`<h4>Umbrales y actuaciones · últimas 48 horas</h4><p class="field-help">Órdenes al relé, no confirmación física de funcionamiento. El gráfico muestra la respuesta posterior; no atribuye una causa.</p>${items.length?items.slice(0,shown).map(({e,d})=>`<article class="environment-action"><strong>${esc(new Date(e.occurredAt).toLocaleString('es-AR'))} · ${esc(d.state)}${d.value==null?'':` · ${d.value.toFixed(2)} kPa`}</strong><p>${d.actions.map(a=>`${esc(a.label)}: ${a.on?'ON':'OFF'} · ${esc(a.mode)}`).join(' / ')|| (d.baseline?'Estado inicial; sin cambio anterior registrado.':'Sin cambio de salidas registrado.')}</p>${d.min!=null?`<small>Objetivo ${d.min}–${d.max} kPa · ${d.enabled?'Control supervisado activo':'Monitoreo; control supervisado desactivado'}</small>`:''}${d.alarms.length?`<p>${esc(d.alarms.join(' '))}</p>`:''}${d.gap?'<p class="field-help">Faltan eventos entre este registro y el anterior.</p>':''}</article>`).join(''):'<p>Sin eventos registrados para estas 48 horas.</p>'}${shown<items.length?'<button id="moreEnvironmentActions" type="button" class="secondary-button">Mostrar más eventos</button>':''}`;const more=$('moreEnvironmentActions');if(more)more.onclick=()=>{shown+=60;draw()}};draw();
}
async function open(metric,address,context={}){const token=++request,device=deviceKey(address),w=CultivoRepository.getCurrentWorkspace?.()?.id;const names={humidity:'Humedad',temperature:'Temperatura',vpd:'VPD y actuaciones'};$('environmentHistoryTitle').textContent=`${names[metric]} · ${context.roomName||'Sala'}`;$('environmentHistoryStats').innerHTML='<p>Cargando…</p>';$('environmentHistoryChart').innerHTML='';$('environmentHistoryActions').innerHTML='';$('environmentHistoryNote').textContent='';$('environmentHistoryDialog').showModal();try{if(!w)throw new Error('Sin proyecto');const [readings,samples,events]=await Promise.all([CultivoRepository.getEnvironmentReadings(device,48),context.roomId?CultivoRepository.getEnvironmentSamples(context.roomId,48):[],metric==='vpd'&&context.roomId?CultivoRepository.getEnvironmentEvents(context.roomId,48):[]]);if(token!==request||w!==CultivoRepository.getCurrentWorkspace()?.id)return;const snapshots=new Map(samples.map(r=>[Math.floor(r.at/SAMPLE),r])),rows=readings.map(r=>({...r,...snapshots.get(Math.floor(r.at/SAMPLE))}));for(const r of samples)if(!rows.some(x=>Math.floor(x.at/SAMPLE)===Math.floor(r.at/SAMPLE)))rows.push(r);render(rows.sort((a,b)=>a.at-b.at),metric,'cloud');if(metric==='vpd')renderActions(events)}catch(error){if(token!==request)return;render(localRows(device),metric,'local');$('environmentHistoryNote').textContent+=' No se pudo consultar el histórico remoto: '+error.message;if(metric==='vpd')$('environmentHistoryActions').textContent='Eventos remotos no disponibles; consultá la Bitácora al recuperar la conexión.'}}
globalThis.EnvironmentHistory=Object.freeze({track,open,valid});
})();
