(()=>{'use strict';
  const KEY='growmanager.environment.v1',WINDOW=24*60*60*1000,SAMPLE=5*60*1000,MAX=300,$=id=>document.getElementById(id);let lastCloudSync=0;
  const finite=value=>value!==null&&value!==''&&Number.isFinite(Number(value));
  const valid=(temperature,humidity)=>finite(temperature)&&finite(humidity)&&!(Number(temperature)===0&&Number(humidity)===0)&&Number(temperature)>=-20&&Number(temperature)<=80&&Number(humidity)>=0&&Number(humidity)<=100;
  const deviceKey=address=>String(address||'primary-wemos').trim().toLowerCase().replace(/[^a-z0-9.:-]/g,'-').slice(0,80)||'primary-wemos';
  function load(){try{const rows=JSON.parse(localStorage.getItem(KEY));return Array.isArray(rows)?rows:[]}catch{return[]}}
  function save(rows){localStorage.setItem(KEY,JSON.stringify(rows.slice(-MAX)))}
  function localRows(device){const now=Date.now(),validRows=load().filter(row=>now-row.at<=WINDOW&&valid(row.temperature,row.humidity)),matching=validRows.filter(row=>row.device===device);return(matching.length?matching:validRows).sort((a,b)=>a.at-b.at)}
  function track(status,address){if(!valid(status?.temperature,status?.humidity))return false;const now=Date.now(),device=deviceKey(address),all=load(),rows=all.filter(row=>now-row.at<=WINDOW),last=[...rows].reverse().find(row=>row.device===device),sample=last&&now-last.at<SAMPLE?last:{at:now,temperature:Number(status.temperature),humidity:Number(status.humidity),device};if(sample!==last){rows.push(sample);save(rows)}if(now-lastCloudSync>SAMPLE&&globalThis.CultivoRepository?.getCurrentWorkspace?.()){lastCloudSync=now;CultivoRepository.saveEnvironmentReading({deviceKey:device,sampledAt:sample.at,temperature:sample.temperature,humidity:sample.humidity}).catch(error=>{lastCloudSync=0;console.warn('No se pudo sincronizar la muestra ambiental:',error)})}return sample!==last}
  function points(rows,key,min,max){const left=42,right=776,top=18,bottom=220,span=Math.max(.1,max-min),start=Date.now()-WINDOW;return rows.map(row=>`${left+((row.at-start)/WINDOW)*(right-left)},${bottom-((row[key]-min)/span)*(bottom-top)}`).join(' ')}
  function stats(rows,key,unit){const values=rows.map(row=>row[key]).filter(finite);if(!values.length)return'<div><span>Sin muestras</span><strong>—</strong></div>';const avg=values.reduce((a,b)=>a+b,0)/values.length;return`<div><span>Mínima</span><strong>${Math.min(...values).toFixed(1)} ${unit}</strong></div><div><span>Promedio</span><strong>${avg.toFixed(1)} ${unit}</strong></div><div><span>Máxima</span><strong>${Math.max(...values).toFixed(1)} ${unit}</strong></div>`}
  function render(rows,metric,config,source){const temp=rows.map(row=>row.temperature).filter(finite),hum=rows.map(row=>row.humidity).filter(finite),focus=metric==='humidity'?'humidity':'temperature',all=focus==='temperature'?temp:hum,unit=focus==='temperature'?'°C':'%',fallback=focus==='temperature'?[18,32]:[30,90],min=all.length?Math.floor(Math.min(...all)-1):fallback[0],max=all.length?Math.ceil(Math.max(...all)+1):fallback[1];$('environmentHistoryStats').innerHTML=stats(rows,focus,unit);const tempMin=temp.length?Math.floor(Math.min(...temp)-1):18,tempMax=temp.length?Math.ceil(Math.max(...temp)+1):32,humMin=hum.length?Math.floor(Math.min(...hum)-2):30,humMax=hum.length?Math.ceil(Math.max(...hum)+2):90,grid=[18,68,118,168,220].map((y,index)=>`<line class="environment-grid" x1="42" y1="${y}" x2="776" y2="${y}"/><text class="environment-axis" x="4" y="${y+4}">${(max-(max-min)*(index/4)).toFixed(0)}${unit}</text>`).join(''),labels=[0,6,12,18,24].map((hour,index)=>`<text class="environment-axis" x="${42+index*183.5}" y="245" text-anchor="middle">-${24-hour} h</text>`).join('');$('environmentHistoryChart').innerHTML=`<svg viewBox="0 0 800 255" preserveAspectRatio="none" aria-hidden="true">${grid}${labels}${rows.length>1?`<polyline class="environment-temp-path" points="${points(rows,'temperature',tempMin,tempMax)}"/><polyline class="environment-humidity-path" points="${points(rows,'humidity',humMin,humMax)}"/>`:''}</svg>`;$('environmentHistoryNote').textContent=rows.length>1?`${rows.length} muestras ${source==='cloud'?'sincronizadas en el proyecto':'del respaldo local'}. Intervalo aproximado: 5 minutos.${config?.lightStartHour!=null?' Podés comparar los cambios entre luz y oscuridad usando el eje horario.':''}`:source==='cloud'?'Todavía no hay suficientes muestras válidas sincronizadas.':'El histórico comenzará a completarse cuando el Wemos entregue lecturas válidas.'}
  async function open(metric,address,config){const device=deviceKey(address);$('environmentHistoryTitle').textContent=metric==='humidity'?'Histórico de humedad':'Histórico de temperatura';$('environmentHistoryStats').innerHTML='<div><span>Sincronizando</span><strong>…</strong></div>';$('environmentHistoryChart').innerHTML='';$('environmentHistoryNote').textContent='Cargando el histórico compartido…';$('environmentHistoryDialog').showModal();try{if(!globalThis.CultivoRepository?.getCurrentWorkspace?.())throw new Error('Sin proyecto');const rows=await CultivoRepository.getEnvironmentReadings(device,24);render(rows,metric,config,'cloud')}catch(error){console.warn('Histórico ambiental local:',error);render(localRows(device),metric,config,'local')}}
  globalThis.EnvironmentHistory=Object.freeze({track,open,valid});
})();
