(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bucket=()=>GrowSupabase.client.storage.from('journal-photos');
let uploading=false;
function gallery(record){return (record.metadata?.photos||[]).length?`<div class="journal-photos">${record.metadata.photos.map(p=>`<a data-photo-path="${esc(p.path)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir ${esc(p.name||'foto')}"><img alt="${esc(p.name||'Foto del cultivo')}" loading="lazy"><span>Foto</span></a>`).join('')}</div>`:''}
async function hydrate(scope=document){await Promise.all([...scope.querySelectorAll('[data-photo-path]')].map(async a=>{if(a.dataset.loaded)return;a.dataset.loaded='true';const{data,error}=await bucket().createSignedUrl(a.dataset.photoPath,3600);if(error){a.querySelector('span').textContent='Foto no disponible';return}if(a.isConnected){a.href=data.signedUrl;a.querySelector('img').src=data.signedUrl;a.querySelector('span').hidden=true}}))}
async function open(cultivationId='',record=null){if(!['owner','editor'].includes(CultivoRepository.getCurrentWorkspace()?.role))return;const workspace=CultivoRepository.getCurrentWorkspace()?.id;const crops=await CultivoRepository.getAll('cultivations');if(workspace!==CultivoRepository.getCurrentWorkspace()?.id)return;let dialog=$('journalPhotosDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='journalPhotosDialog';dialog.className='app-dialog';document.body.append(dialog)}
dialog.innerHTML=`<form class="dialog-form"><h3>${record?'Agregar fotos al registro':'Fotos de diagnóstico'}</h3><label>Cultivo<select name="cultivationId" required ${record?'disabled':''}><option value="">Elegí un cultivo</option>${crops.map(c=>`<option value="${c.id}" ${c.id===cultivationId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${record?'':`<label>Título<input name="title" required maxlength="120" value="Fotos de diagnóstico"></label><label>Observación<textarea name="notes" rows="3" maxlength="1200"></textarea></label>`}<label>Fotos<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple required></label><small>Hasta 8 fotos por carga · JPG, PNG o WebP · 10 MB por foto.</small><p role="status"></p><div class="form-actions"><button type="button" class="secondary-button">Cancelar</button><button type="submit" class="primary-button">Guardar fotos</button></div></form>`;
dialog.querySelector('[type=button]').onclick=()=>{if(!uploading)dialog.close()};dialog.oncancel=e=>{if(uploading)e.preventDefault()};
dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(uploading)return;const f=e.target,files=[...f.elements.photos.files],crop=crops.find(c=>c.id===f.elements.cultivationId.value),status=f.querySelector('[role=status]');let log=record,created=false,saved=false,paths=[];try{
if(workspace!==CultivoRepository.getCurrentWorkspace()?.id)throw new Error('El proyecto cambió. Volvé a abrir el formulario.');if(!crop)throw new Error('Elegí un cultivo.');if(files.length<1||files.length>8)throw new Error('Seleccioná entre 1 y 8 fotos.');for(const file of files)if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760)throw new Error('Cada foto debe ser JPG, PNG o WebP y pesar hasta 10 MB.');
uploading=true;e.submitter.disabled=true;status.textContent='Subiendo fotos…';if(!log){const lots=await CultivoRepository.getAll('lots'),lot=lots.find(l=>l.cultivationId===crop.id);log=await CultivoRepository.createOperationLog({kind:'activity',category:'observation',title:f.elements.title.value,description:f.elements.notes.value,severity:'info',occurredAt:new Date().toISOString(),metadata:{cultivationId:crop.id,cultivationName:crop.name,lotId:lot?.id||null,source:'diagnostic_photos'}});created=true}
const photos=[];for(const file of files){const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type],path=`${workspace}/${crop.id}/${log.id}/${crypto.randomUUID()}.${ext}`;const{error}=await bucket().upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;paths.push(path);photos.push({path,name:file.name.slice(0,150),uploadedAt:new Date().toISOString()})}
await CultivoRepository.cropAction('append_journal_photos',{p_log:log.id,p_photos:photos});saved=true;dialog.close();await Operations.load();await GrowToday.refreshCrop();
}catch(error){if(!saved){if(paths.length)await bucket().remove(paths);if(created&&log)await CultivoRepository.remove('operation_logs',log.id);status.textContent=error.message||'No se pudieron subir las fotos.'}else{const n=$('operationsMessage');n.textContent='Fotos guardadas. Actualizá el historial para verlas.';n.className='message show success'}}finally{uploading=false;f.querySelector('[type=submit]').disabled=false}};dialog.showModal()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-journal-photos]');if(!b)return;try{let record=null;if(b.dataset.photoLog){record=(await CultivoRepository.getOperationLogs()).find(r=>r.id===b.dataset.photoLog);if(!record)throw new Error('El registro ya no está disponible.')}await open(b.dataset.journalPhotos,record)}catch(error){const n=$('operationsMessage');n.textContent=error.message;n.className='message show error'}});
globalThis.GrowPhotos=Object.freeze({open,gallery,hydrate});
})();
