(()=>{'use strict';
const $=id=>document.getElementById(id);
const steps=[
  {view:'dashboard',selector:'[data-view-panel="dashboard"] .page-heading',icon:'⌂',title:'Inicio',description:'Acá tenés el estado general: ambiente, próximos eventos, cultivos concurrentes y control rápido del dispositivo.'},
  {view:'cultivation',selector:'[data-view-panel="cultivation"] .page-heading',icon:'✦',title:'Cultivo',description:'Organizá ciclos, espacios, lotes y plantas. Cada proyecto mantiene sus propios datos y permisos.'},
  {view:'agenda',selector:'[data-view-panel="agenda"] .page-heading',icon:'▣',title:'Agenda y nutrición',description:'Visualizá eventos, responsables, etapas del cultivo y calendario nutricional sobre las fechas reales.'},
  {view:'operations',selector:'[data-view-panel="operations"] .page-heading',icon:'☷',title:'Bitácora',description:'Registrá riegos, podas, trasplantes, observaciones e incidentes para conservar toda la trazabilidad.'},
  {view:'assistant',selector:'[data-view-panel="assistant"] .page-heading',icon:'✦',title:'Asistente IA',description:'Consultá, planificá y prepará registros con lenguaje natural. Siempre revisás las acciones antes de guardarlas.'},
  {view:'control',selector:'[data-view-panel="control"] .page-heading',icon:'◉',title:'Control y hardware',description:'Configurá el Wemos, automatizaciones, ventilación, sensores y energía. Esta parte trabaja con tu dispositivo local.'},
  {view:'team',selector:'[data-view-panel="team"] .page-heading',icon:'◎',title:'Proyectos y miembros',description:'Gestioná tus proyectos, invitaciones y permisos. Los miembros comunes nunca pueden ver proyectos para los que no tienen acceso.'}
];
let index=0,ready=false;
function showView(view){document.querySelector(`[data-view="${view}"]`)?.click()}
function clearHighlight(){document.querySelectorAll('.tour-highlight').forEach(node=>node.classList.remove('tour-highlight'))}
function render(){const step=steps[index];showView(step.view);clearHighlight();const target=document.querySelector(step.selector);target?.classList.add('tour-highlight');target?.scrollIntoView({block:'center',behavior:'smooth'});$('tourIcon').textContent=step.icon;$('tourTitle').textContent=step.title;$('tourDescription').textContent=step.description;$('tourEyebrow').textContent=`RECORRIDO · ${index+1} DE ${steps.length}`;$('tourPrevious').disabled=index===0;$('tourNext').textContent=index===steps.length-1?'Finalizar':'Siguiente';$('tourProgress').innerHTML=steps.map((_,i)=>`<i class="${i<=index?'active':''}"></i>`).join('')}
async function finish(){clearHighlight();$('appTourDialog').close();await CultivoRepository.completeOnboarding().catch(console.warn);showView('dashboard')}
function start(){index=0;$('projectHubDialog')?.close();if(!$('appTourDialog').open)$('appTourDialog').show();render()}
async function maybeStart(){try{const state=await CultivoRepository.getOnboardingState();if(state.completed)return;const dialog=$('welcomeWizardDialog');if(!dialog.open)dialog.showModal()}catch(error){console.warn('No se pudo iniciar el onboarding:',error)}}
function init(){if(ready)return;ready=true;$('welcomeWizardForm').addEventListener('change',event=>{if(event.target.name==='mode')$('welcomeProjectName').hidden=event.target.value==='demo'});$('welcomeWizardForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),button=event.submitter,status=$('welcomeWizardMessage');button.disabled=true;status.className='message show info';status.textContent='Preparando tu experiencia…';try{if(data.mode==='demo'){const demo=CultivoRepository.getWorkspaces().find(item=>item.isDemo);if(demo)await CultivoRepository.setCurrentWorkspace(demo.id)}else await CultivoRepository.createOnboardingWorkspace(data.name.trim(),data.mode);await Workspaces.load();$('welcomeWizardDialog').close();start()}catch(error){status.className='message show error';status.textContent=error.message}finally{button.disabled=false}});$('welcomeSkipTour').addEventListener('click',async()=>{await CultivoRepository.completeOnboarding();$('welcomeWizardDialog').close()});$('tourPrevious').addEventListener('click',()=>{if(index>0){index--;render()}});$('tourNext').addEventListener('click',()=>{if(index===steps.length-1)finish();else{index++;render()}});$('tourExit').addEventListener('click',finish);$('startTourButton').addEventListener('click',start)}
globalThis.OnboardingTour=Object.freeze({init,maybeStart,start});
})();
