(() => {
  'use strict';
  const M=()=>globalThis.CultivoModels;
  const esc=value=>{const node=document.createElement('div');node.textContent=String(value??'');return node.innerHTML};
  let root,products=[],search='',filter='active';

  function message(text,type='success'){const node=root.querySelector('#productsMessage');node.textContent=text;node.className=`message show ${type}`}
  function filtered(){return products.filter(item=>(filter==='all'||filter==='active'&&item.active||filter==='inactive'&&!item.active)&&`${item.name} ${item.brand}`.toLowerCase().includes(search.toLowerCase()))}
  function render(){
    const list=filtered();
    root.innerHTML=`<div id="productsMessage" class="message"></div><div class="toolbar"><label class="search-field">Buscar producto<input id="productSearch" type="search" value="${esc(search)}" placeholder="Nombre o marca"></label><label>Estado<select id="productFilter"><option value="active" ${filter==='active'?'selected':''}>Activos</option><option value="inactive" ${filter==='inactive'?'selected':''}>Inactivos</option><option value="all" ${filter==='all'?'selected':''}>Todos</option></select></label><button class="primary-button" data-product-action="new">+ Producto</button></div>${list.length?`<div class="product-grid">${list.map(item=>`<article class="panel product-card ${item.active?'':'is-inactive'}"><div><span class="type-chip">${M().PRODUCT_TYPE_LABELS[item.type]}</span><h3>${esc(item.name)}</h3><p>${esc(item.brand||'Sin marca')}</p></div><div class="product-meta"><span>Unidad base <strong>${M().UNIT_LABELS[item.baseUnit]}</strong></span><span>${item.active?'Activo':'Inactivo'}</span></div>${item.description?`<p class="card-copy">${esc(item.description)}</p>`:''}<div class="inline-actions"><button class="text-button" data-product-action="edit" data-id="${item.id}">Editar</button><button class="text-button" data-product-action="toggle" data-id="${item.id}">${item.active?'Desactivar':'Activar'}</button></div></article>`).join('')}</div>`:`<section class="panel empty-state compact-empty"><span class="empty-icon">◈</span><h3>${products.length?'No hay productos para este filtro':'Todavía no agregaste productos'}</h3><p>${products.length?'Probá otra búsqueda o filtro.':'Los productos serán los componentes de tus recetas.'}</p>${products.length?'':'<button class="primary-button" data-product-action="new">Agregar producto</button>'}</section>`}<dialog id="productDialog" class="app-dialog"></dialog>`;
  }
  function open(id=null){
    const item=products.find(value=>value.id===id)||{};const dialog=root.querySelector('#productDialog');
    const baseUnits=['g','ml','l','percent','other'];
    dialog.innerHTML=`<form method="dialog" class="dialog-form" data-product-form data-id="${id||''}"><div class="dialog-heading"><div><p class="eyebrow">${id?'EDITAR':'NUEVO'}</p><h3>Producto</h3></div><button class="icon-button" value="cancel" aria-label="Cerrar">×</button></div><label>Nombre<input name="name" value="${esc(item.name||'')}" maxlength="80" required></label><label>Marca<input name="brand" value="${esc(item.brand||'')}" maxlength="80"></label><div class="form-grid two"><label>Tipo<select name="type">${M().PRODUCT_TYPES.map(code=>`<option value="${code}" ${code===(item.type||'fertilizer')?'selected':''}>${M().PRODUCT_TYPE_LABELS[code]}</option>`).join('')}</select></label><label>Unidad base<select name="baseUnit">${baseUnits.map(code=>`<option value="${code}" ${code===(item.baseUnit||'g')?'selected':''}>${M().UNIT_LABELS[code]}</option>`).join('')}</select></label></div><label>Descripción<textarea name="description" rows="2">${esc(item.description||'')}</textarea></label><label>Notas<textarea name="notes" rows="2">${esc(item.notes||'')}</textarea></label><label class="check-field"><input name="active" type="checkbox" ${item.active!==false?'checked':''}> Producto activo</label><div class="form-actions split"><button class="secondary-button" value="cancel">Cancelar</button><button class="primary-button" type="submit" value="default">Guardar</button></div></form>`;dialog.showModal();
  }
  async function load(){products=(await CultivoRepository.getAll('products')).sort((a,b)=>a.name.localeCompare(b.name,'es'));render()}
  async function submit(event){const form=event.target.closest('[data-product-form]');if(!form)return;event.preventDefault();const data=Object.fromEntries(new FormData(form));const id=form.dataset.id||null;try{const value=M().assertValid(M().validateProduct({...data,description:M().normalizeText(data.description),notes:M().normalizeText(data.notes),active:data.active==='on'}));if(id)await CultivoRepository.update('products',id,value);else await CultivoRepository.create('products',value);form.closest('dialog').close();await load();message('Producto guardado correctamente.')}catch(error){message(error.message,'error')}}
  async function click(event){const button=event.target.closest('[data-product-action]');if(!button)return;const action=button.dataset.productAction;if(action==='new')open();if(action==='edit')open(button.dataset.id);if(action==='toggle'){const item=products.find(v=>v.id===button.dataset.id);await CultivoRepository.setActive('products',item.id,!item.active);await load();message(`Producto ${item.active?'desactivado':'activado'}.`)}}
  function input(event){if(event.target.id==='productSearch'){search=event.target.value;render();const field=root.querySelector('#productSearch');field.focus();field.setSelectionRange(search.length,search.length)}if(event.target.id==='productFilter'){filter=event.target.value;render()}}
  function init(){root=document.getElementById('productsRoot');root.addEventListener('click',click);root.addEventListener('submit',submit);root.addEventListener('input',input);root.addEventListener('change',input)}
  globalThis.Products=Object.freeze({init,load});
})();
