import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const nodes=new Map();
const get=id=>{if(!nodes.has(id))nodes.set(id,{value:'',dataset:{},textContent:'',innerHTML:'',hidden:false});return nodes.get(id)};
const calls=[];
const status=(room,t)=>({temperature:t,humidity:60,dht:{fresh:true},environment:{roomId:room,vpdMin:.8,vpdMax:1.2},relays:[{id:1,function:'light',state:t===22}]});
const remote=[{room_id:'flora',device_key:'flora-device',sampled_at:new Date().toISOString(),payload:status('flora',22)}];
const ctx=vm.createContext({console,Date,setInterval(){},addEventListener(){},localStorage:{setItem(){}},document:{getElementById:id=>['environmentEvents','environmentRemoteMessage','environmentRoom'].includes(id)?null:get(id),querySelectorAll:()=>[],createElement:()=>({}),body:{append(){}},addEventListener(){}},CultivoRepository:{getCurrentWorkspace:()=>({id:'project',role:'owner'}),getAll:async table=>table==='rooms'?[{id:'vege',name:'Vegetativo'},{id:'flora',name:'Flora'}]:[]},GrowSupabase:{client:{from:table=>({select(){return this},eq(){return this},order(){return this},limit(){return this},then(resolve){resolve({data:table==='environment_status'?remote:[]})}})}},GrowDevice:{address:()=> 'local-device',renderRemoteRelays:(r,f)=>calls.push({r,f})}});
vm.runInContext(readFileSync(new URL('../environment-models.js',import.meta.url),'utf8'),ctx);
vm.runInContext(readFileSync(new URL('../environment.js',import.meta.url),'utf8'),ctx);
ctx.GrowEnvironmentUI.init();await ctx.GrowEnvironmentUI.loadRooms();
assert.equal(get('dashboardEnvironmentRoom').value,'flora','Default selects a room that has telemetry');
assert.equal(get('temperature').textContent,'22.0');assert.equal(ctx.GrowEnvironmentUI.historyDevice(),'flora-device');assert.equal(calls.at(-1).r[0].state,true);
ctx.GrowEnvironmentUI.update(status('vege',19));
assert.equal(get('temperature').textContent,'22.0','Local device in another room must not replace selected remote data');
get('dashboardEnvironmentRoom').value='vege';get('dashboardEnvironmentRoom').onchange();
assert.equal(get('temperature').textContent,'19.0');assert.equal(calls.at(-1).r[0].state,false);
ctx.GrowEnvironmentUI.offline();assert.equal(get('temperature').textContent,'—');assert.equal(calls.at(-1).r.length,0,'No devices from a different room remain displayed');
console.log('Room selection, remote equipment and room-scoped history: passed');
