import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const schema=await readFile(new URL('../supabase/migrations/202608260001_initial_schema.sql',import.meta.url),'utf8');
const rls=await readFile(new URL('../supabase/migrations/202608260002_rls.sql',import.meta.url),'utf8');
const functions=await readFile(new URL('../supabase/migrations/202608260003_recipe_functions.sql',import.meta.url),'utf8');
const collaboration=await readFile(new URL('../supabase/migrations/202608260005_collaboration.sql',import.meta.url),'utf8');
const agenda=await readFile(new URL('../supabase/migrations/202608260006_project_agenda.sql',import.meta.url),'utf8');
const cascadeDelete=await readFile(new URL('../supabase/migrations/202608270007_workspace_cascade_delete.sql',import.meta.url),'utf8');
const memberManagement=await readFile(new URL('../supabase/migrations/202608310008_member_management_assignments.sql',import.meta.url),'utf8');
const tables=['profiles','cultivations','spaces','lots','plants','products','recipes','recipe_versions','recipe_items','activities'];
for(const table of tables){assert.match(schema,new RegExp(`create table public\\.${table} \\(`));assert.match(rls,new RegExp(`public\\.${table}`))}
assert.doesNotMatch(rls,/using\s*\(\s*true\s*\)/i);
assert.doesNotMatch(`${schema}\n${rls}\n${functions}`,/service_role|postgres(?:ql)?:\/\//i);
assert.match(rls,/revoke all on table/);
assert.match(rls,/to authenticated/);
assert.match(functions,/security invoker/);
assert.match(functions,/create_recipe_with_version/);
assert.match(functions,/create_recipe_version/);
for(const table of ['workspaces','workspace_members','workspace_invitations'])assert.match(collaboration,new RegExp(`create table public\\.${table}`));
for(const fn of ['is_workspace_member','can_edit_workspace','create_workspace','invite_workspace_member','accept_workspace_invitation','list_workspace_members'])assert.match(collaboration,new RegExp(`function public\\.${fn}`));
assert.match(collaboration,/workspace_id uuid/);
assert.match(collaboration,/force row level security/i);
assert.doesNotMatch(collaboration,/using\s*\(\s*true\s*\)/i);
assert.doesNotMatch(collaboration,/service_role/i);
assert.match(agenda,/create table public\.irrigation_events/);
assert.match(agenda,/create policy irrigation_events_select_workspace/);
assert.match(agenda,/public\.can_edit_workspace\(workspace_id\)/);
assert.match(agenda,/add column grow_type/);
assert.match(agenda,/function public\.delete_workspace/);
assert.match(agenda,/workspace_not_empty/);
assert.doesNotMatch(agenda,/using\s*\(\s*true\s*\)/i);
for(const table of ['irrigation_events','activities','plants','lots','spaces','recipe_items','recipe_versions','recipes','products','cultivations','workspaces'])assert.match(cascadeDelete,new RegExp(`delete from public\\.${table}`));
assert.match(cascadeDelete,/is_workspace_owner/);
assert.match(memberManagement,/add column assigned_to uuid references auth\.users\(id\) on delete set null/);
for(const fn of ['update_workspace_member_role','remove_workspace_member','cancel_workspace_invitation','assign_irrigation_event'])assert.match(memberManagement,new RegExp(`function public\\.${fn}`));
assert.match(memberManagement,/assignee_not_workspace_member/);
assert.match(memberManagement,/workspace_owner_cannot_be_removed/);
assert.doesNotMatch(memberManagement,/service_role|using\s*\(\s*true\s*\)/i);
console.log('supabase-schema: estructura y RLS correctos');
