import { createClient } from 'npm:@supabase/supabase-js@2'

const allowedOrigins=new Set(['https://maindave.github.io','http://127.0.0.1:8081','http://localhost','capacitor://localhost'])
const headers=(origin:string)=>({'Access-Control-Allow-Origin':allowedOrigins.has(origin)?origin:'https://maindave.github.io','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, x-application-name, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'})
const ids={type:'STRING',description:'ID exacto del contexto; omitir si no corresponde'}
const tools=[{functionDeclarations:[
  {name:'registrar_actividad_bitacora',description:'Registrar una actividad ya realizada o una nota de trazabilidad.',parameters:{type:'OBJECT',required:['titulo','tipo','detalles','fecha'],properties:{titulo:{type:'STRING'},tipo:{type:'STRING',enum:['general','transplant','pruning','pests','fungus','lighting','maintenance','power']},detalles:{type:'STRING'},fecha:{type:'STRING',description:'Fecha y hora ISO 8601'},cultivationId:ids,lotId:ids,recetaId:ids,severity:{type:'STRING',enum:['info','warning','critical']}}}},
  {name:'registrar_incidente',description:'Registrar un incidente, anomalía, corte, plaga o problema ya ocurrido.',parameters:{type:'OBJECT',required:['titulo','tipo','detalles','fecha','severity'],properties:{titulo:{type:'STRING'},tipo:{type:'STRING',enum:['general','irrigation','pests','fungus','lighting','maintenance','power']},detalles:{type:'STRING'},fecha:{type:'STRING'},cultivationId:ids,lotId:ids,severity:{type:'STRING',enum:['warning','critical']}}}},
  {name:'registrar_riego',description:'Registrar un riego ya realizado, vinculándolo a lote y receta cuando se puedan identificar sin ambigüedad.',parameters:{type:'OBJECT',required:['titulo','fecha','detalles'],properties:{titulo:{type:'STRING'},fecha:{type:'STRING'},detalles:{type:'STRING'},cultivationId:ids,lotId:ids,recetaId:ids,waterLiters:{type:'NUMBER'},ph:{type:'NUMBER'},ec:{type:'NUMBER'},supplies:{type:'ARRAY',items:{type:'OBJECT',properties:{name:{type:'STRING'},amount:{type:'NUMBER'},unit:{type:'STRING'}}}}}}},
  {name:'crear_evento_calendario',description:'Crear una actividad futura en la agenda.',parameters:{type:'OBJECT',required:['titulo','fechaInicio','tipo'],properties:{titulo:{type:'STRING'},fechaInicio:{type:'STRING'},fechaFin:{type:'STRING'},tipo:{type:'STRING',enum:['irrigation','transplant','cuttings','pruning','fertilization','pests','fungus','lighting','cleaning','harvest','maintenance','other']},cultivationId:ids,lotId:ids,descripcion:{type:'STRING'},prioridad:{type:'STRING',enum:['low','normal','high','urgent']}}}},
  {name:'actualizar_evento_calendario',description:'Modificar un evento existente identificado sin ambigüedad.',parameters:{type:'OBJECT',required:['eventId'],properties:{eventId:ids,titulo:{type:'STRING'},fechaInicio:{type:'STRING'},fechaFin:{type:'STRING'},tipo:{type:'STRING'},descripcion:{type:'STRING'},prioridad:{type:'STRING'},status:{type:'STRING'}}}},
  {name:'planificar_cultivo',description:'Crear una nueva tanda/lote y sus hitos de agenda cuando hay fecha y duración suficientes.',parameters:{type:'OBJECT',required:['lot','events'],properties:{cultivationId:ids,spaceId:ids,cultivation:{type:'OBJECT',properties:{name:{type:'STRING'},startDate:{type:'STRING'},plannedEndDate:{type:'STRING'},cultivationMode:{type:'STRING'},currentStage:{type:'STRING'},stageStartedOn:{type:'STRING'},notes:{type:'STRING'}}},space:{type:'OBJECT',properties:{name:{type:'STRING'},description:{type:'STRING'},operationalStage:{type:'STRING'}}},lot:{type:'OBJECT',required:['name','stage','timelineStartedOn'],properties:{name:{type:'STRING'},description:{type:'STRING'},stage:{type:'STRING'},timelineStartedOn:{type:'STRING'},timelineEndOn:{type:'STRING'},showOnCalendar:{type:'BOOLEAN'}}},events:{type:'ARRAY',items:{type:'OBJECT',required:['title','eventType','startsAt'],properties:{title:{type:'STRING'},eventType:{type:'STRING'},startsAt:{type:'STRING'},endsAt:{type:'STRING'},description:{type:'STRING'},priority:{type:'STRING'},status:{type:'STRING'}}}}}}}
]}]
const instruction=`Sos el asistente operativo de GrowManager. Respondé en español rioplatense, claro y breve. Interpretá relatos naturales sobre el cultivo y usá las herramientas para proponer acciones estructuradas. Podés llamar varias herramientas en una respuesta: por ejemplo registrar un riego concluido, una observación y un próximo control. Las llamadas NO ejecutan nada: la app las muestra y el usuario confirma el conjunto antes de guardarlo.
Reglas: no inventes fechas, cantidades, mediciones, recetas ni relaciones. Usá solamente IDs exactos del contexto. Si una receta, lote, cultivo o evento es ambiguo, explicá qué falta y no llames la herramienta afectada. Una acción pasada va a bitácora; una acción futura va a calendario. Para un riego ya realizado usá registrar_riego, no crear_evento_calendario. La IA sugiere y el usuario decide. Nunca controles relays, bombas, calefacción ni firmware. La telemetría/configuración del Wemos aparece en deviceContext. Priorizá los datos vivos del contexto.`
const mapping:Record<string,(a:any)=>any>={
  registrar_actividad_bitacora:a=>({type:'record_activity',summary:a.titulo,payload:{title:a.titulo,category:a.tipo,description:a.detalles,occurredAt:a.fecha,cultivationId:a.cultivationId,lotId:a.lotId,recipeId:a.recetaId,severity:a.severity||'info'}}),
  registrar_incidente:a=>({type:'record_incident',summary:a.titulo,payload:{title:a.titulo,category:a.tipo,description:a.detalles,occurredAt:a.fecha,cultivationId:a.cultivationId,lotId:a.lotId,severity:a.severity}}),
  registrar_riego:a=>({type:'record_irrigation',summary:a.titulo,payload:{title:a.titulo,occurredAt:a.fecha,details:a.detalles,cultivationId:a.cultivationId,lotId:a.lotId,recipeId:a.recetaId,waterLiters:a.waterLiters,ph:a.ph,ec:a.ec,supplies:a.supplies||[]}}),
  crear_evento_calendario:a=>({type:'create_event',summary:a.titulo,payload:{title:a.titulo,startsAt:a.fechaInicio,endsAt:a.fechaFin,eventType:a.tipo,cultivationId:a.cultivationId,lotId:a.lotId,description:a.descripcion,priority:a.prioridad||'normal',status:'pending'}}),
  actualizar_evento_calendario:a=>({type:'update_event',summary:a.titulo||'Actualizar evento',payload:{eventId:a.eventId,title:a.titulo,startsAt:a.fechaInicio,endsAt:a.fechaFin,eventType:a.tipo,description:a.descripcion,priority:a.prioridad,status:a.status}}),
  planificar_cultivo:a=>({type:'plan_cultivation',summary:`Planificar ${a.lot?.name||'cultivo'}`,payload:a})
}

Deno.serve(async req=>{const origin=req.headers.get('Origin')||'',cors=headers(origin),json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});if(req.method==='OPTIONS')return allowedOrigins.has(origin)?new Response('ok',{headers:cors}):json({error:'origin_not_allowed'},403);if(req.method!=='POST')return json({error:'method_not_allowed'},405);if(origin&&!allowedOrigins.has(origin))return json({error:'origin_not_allowed'},403);
try{const authorization=req.headers.get('Authorization')||'';if(!authorization.startsWith('Bearer '))return json({error:'authentication_required'},401);const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_ANON_KEY');if(!key)return json({error:'supabase_key_not_configured'},503);const db=createClient(url,key,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await db.auth.getUser();if(!user)return json({error:'authentication_required'},401);const body=await req.json(),message=String(body?.message||'').trim(),workspaceId=String(body?.workspaceId||'');if(!message||message.length>4000)return json({error:'invalid_message'},400);if(!/^[0-9a-f-]{36}$/i.test(workspaceId))return json({error:'invalid_workspace'},400);const{data:member}=await db.from('workspace_members').select('role').eq('workspace_id',workspaceId).eq('user_id',user.id).maybeSingle();if(!member)return json({error:'workspace_access_denied'},403);
const query=async(table:string,select:string,limit=80)=>{const{data,error}=await db.from(table).select(select).eq('workspace_id',workspaceId).limit(limit);if(error)throw error;return data||[]};const[{data:workspace},cultivations,spaces,lots,recipes,versions,irrigations,activities,events,logs]=await Promise.all([db.from('workspaces').select('id,name,description,grow_type,started_on').eq('id',workspaceId).single(),query('cultivations','id,name,start_date,planned_end_date,cultivation_mode,current_stage,status,notes'),query('spaces','id,cultivation_id,name,description,operational_stage,active'),query('lots','id,cultivation_id,space_id,name,description,stage,timeline_started_on,timeline_end_on,active'),query('recipes','id,name,type,description,notes,active,current_version_id'),query('recipe_versions','id,recipe_id,version,target_ph,target_ec,notes,recipe_items(product_id,product_name_snapshot,amount,unit)'),query('irrigation_events','id,cultivation_id,lot_id,scheduled_at,status,water_liters,ph,ec,notes,supplies'),query('activities','id,cultivation_id,space_id,lot_id,type,occurred_at,observations,details'),query('agenda_events','id,title,event_type,starts_at,ends_at,cultivation_id,lot_id,description,priority,status,archived_at'),query('operation_logs','id,kind,category,title,description,severity,occurred_at,metadata',30)]);
const context={now:new Date().toISOString(),workspace,role:member.role,deviceContext:body.deviceContext||null,cultivations,spaces,lots,recipes,recipeVersions:versions,irrigations,activities,operationLogs:logs,agendaEvents:events.filter((e:any)=>!e.archived_at)};const apiKey=Deno.env.get('GEMINI_API_KEY');if(!apiKey)return json({error:'gemini_not_configured'},503);const contents=[...(Array.isArray(body.history)?body.history.slice(-4):[]).map((x:any)=>({role:x.role==='assistant'?'model':'user',parts:[{text:String(x.text||'').slice(0,1600)}]})),{role:'user',parts:[{text:`PEDIDO:\n${message}\n\nCONTEXTO DEL PROYECTO:\n${JSON.stringify(context).slice(0,36000)}`}]}];const call=()=>fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({system_instruction:{parts:[{text:instruction}]},contents,tools,toolConfig:{functionCallingConfig:{mode:'AUTO'}},generationConfig:{temperature:.15}})});let response=await call();if([429,500,502,503,504].includes(response.status)){await new Promise(r=>setTimeout(r,700));response=await call()}const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||'Gemini API error');const parts=result?.candidates?.[0]?.content?.parts||[],reply=parts.map((p:any)=>p.text||'').join('').trim(),proposals=parts.filter((p:any)=>p.functionCall).map((p:any)=>mapping[p.functionCall.name]?.(p.functionCall.args||{})).filter(Boolean);return json({reply:reply||(proposals.length?`Preparé ${proposals.length} ${proposals.length===1?'acción':'acciones'} para que las revises antes de guardar.`:'Necesito más información para armar una propuesta segura.'),proposals,proposal:proposals[0]||{type:'none',summary:'',payload:{}},requestId:String(body.requestId||'')})
}catch(error){console.error(error);return json({error:'assistant_error',message:`No se pudo procesar la consulta: ${error instanceof Error?error.message:'Error interno'}`},500)}})
